[package]
name = "greentask"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]

[dependencies]
coroutine = { git = "https://github.com/DenisKolodin/coroutine-rs", branch = "cross-data" }

